import { people } from './people'
import type { Skill, SkillAccess, SkillRelease, SkillSource } from './types'
import type { DitherColor } from '@/components/dither-kit'

/** Deterministic 12-week run series with a mild trend, seeded from the skill id. */
function weeklySeries(seed: string, base: number, trend: number): number[] {
  let h = 2166136261
  for (let i = 0; i < seed.length; i++) {
    h ^= seed.charCodeAt(i)
    h = Math.imul(h, 16777619)
  }
  const out: number[] = []
  for (let w = 0; w < 12; w++) {
    h ^= h << 13
    h ^= h >>> 17
    h ^= h << 5
    const noise = (Math.abs(h) % 100) / 100 - 0.5
    out.push(Math.max(1, Math.round(base + trend * w + noise * base * 0.35)))
  }
  return out
}

type SkillSeed = Omit<Skill, 'weeklyRuns' | 'usedBy' | 'source' | 'access'> & {
  runBase: number
  runTrend: number
}

/**
 * Provenance. Anything not listed was written in-house by the owning team —
 * the default for an internal registry.
 */
const sources: Record<string, SkillSource> = {
  'a11y-audit': { kind: 'public', origin: 'github.com/dequelabs/axe-agent-skills' },
  'test-gen': { kind: 'public', origin: 'npm: @vitest/agent-skills' },
  'api-designer': { kind: 'public', origin: 'github.com/stoplightio/spectral-skill' },
  'figma-qa': { kind: 'public', origin: 'figma.com/community/skills/qa-diff' },
  'sales-email': { kind: 'public', origin: 'skillhub.dev/outbound-writer' },
  'user-interview': { kind: 'public', origin: 'github.com/dovetail/interview-synth' },
  'policy-diff': { kind: 'public', origin: 'skillhub.dev/policy-diff' },
}

/** Governance. Unlisted skills are installable company-wide. */
const access: Record<string, SkillAccess> = {
  'contract-review': { scope: 'department', department: 'Legal' },
  'policy-diff': { scope: 'department', department: 'Legal' },
  'deal-brief': { scope: 'department', department: 'Sales' },
  'brand-check': { scope: 'department', department: 'Design' },
  'incident-postmortem': { scope: 'managers' },
  'roadmap-triage': { scope: 'managers' },
  'vendor-audit': { scope: 'board' },
}

const rel = (version: string, date: string, note: string, author: string): SkillRelease => ({
  version,
  date,
  note,
  author,
})

const seeds: SkillSeed[] = [
  {
    id: 'design-polish',
    name: 'Design Polish',
    command: 'design-polish',
    tagline: 'Audits a screen for spacing, hierarchy and contrast, then fixes it.',
    description:
      'Runs a designer-grade pass over any screen or component. It flags inconsistent spacing scales, weak type hierarchy, low-contrast pairs and generic AI-looking layouts, then applies the fixes directly to the code or Figma file. Built by the design systems team from the internal visual QA checklist.',
    category: 'Design',
    tier: 'official',
    version: '3.2.0',
    updatedAt: '2026-07-21',
    owner: 'mina',
    ownerTeam: 'Design',
    installs: 86,
    activeUsers: 61,
    retention: [92, 84, 79, 74],
    minutesSaved: 34,
    color: 'purple',
    runBase: 210,
    runTrend: 26,
    history: [
      rel('3.2.0', '2026-07-21', 'Adds dark-mode contrast checks and a per-fix diff summary.', 'mina'),
      rel('3.1.0', '2026-06-30', 'Detects AI-slop patterns: emoji headers, gradient soup, centered walls of text.', 'dana'),
      rel('3.0.0', '2026-06-02', 'Rewritten around the 8pt spacing scale. Breaking: config key renamed to `scale`.', 'mina'),
      rel('2.4.1', '2026-05-11', 'Fixes false positives on icon-only buttons.', 'dana'),
    ],
  },
  {
    id: 'figma-qa',
    name: 'Figma QA Reviewer',
    command: 'figma-qa',
    tagline: 'Diffs a Figma frame against the shipped build and lists every mismatch.',
    description:
      'Pulls the Figma frame, screenshots the running build, and reports the deltas: off-token colors, wrong type ramp, missing states, spacing drift. Produces a checklist you can paste straight into a PR review.',
    category: 'Design',
    tier: 'official',
    version: '2.0.3',
    updatedAt: '2026-07-14',
    owner: 'dana',
    ownerTeam: 'Design',
    installs: 54,
    activeUsers: 38,
    retention: [88, 76, 70, 64],
    minutesSaved: 41,
    color: 'blue',
    runBase: 120,
    runTrend: 14,
    history: [
      rel('2.0.3', '2026-07-14', 'Handles component variants with nested auto-layout.', 'dana'),
      rel('2.0.0', '2026-06-18', 'Switched to the Figma MCP server. Requires a re-auth.', 'dana'),
      rel('1.6.0', '2026-05-05', 'Adds state coverage: hover, focus, disabled, loading.', 'mina'),
    ],
  },
  {
    id: 'visual-hierarchy',
    name: 'Visual Hierarchy Feedback',
    command: 'visual-hierarchy',
    tagline: 'Ranks what a user sees first and tells you when it is the wrong thing.',
    description:
      'Simulates a first-glance read of the screen, ranks elements by visual weight, and compares that order against the intended user goal. Useful right before a design review when a layout feels flat but nobody can say why.',
    category: 'Design',
    tier: 'recommended',
    version: '1.4.0',
    updatedAt: '2026-07-02',
    owner: 'mina',
    ownerTeam: 'Design',
    installs: 33,
    activeUsers: 21,
    retention: [80, 66, 58, 51],
    minutesSaved: 22,
    color: 'pink',
    runBase: 64,
    runTrend: 7,
    history: [
      rel('1.4.0', '2026-07-02', 'Adds a saliency heatmap overlay to the report.', 'mina'),
      rel('1.2.0', '2026-05-28', 'Scores against the goal statement instead of generic heuristics.', 'mina'),
    ],
  },
  {
    id: 'brand-check',
    name: 'Brand Consistency Checker',
    command: 'brand-check',
    tagline: 'Catches off-brand color, type and voice before anything ships.',
    description:
      'Validates any artifact — a screen, a deck, a landing page, an email — against the brand kit. Reports token violations and rewrites copy that drifts from the voice guide.',
    category: 'Design',
    tier: 'recommended',
    version: '2.1.0',
    updatedAt: '2026-06-25',
    owner: 'lucia',
    ownerTeam: 'Design',
    installs: 41,
    activeUsers: 24,
    retention: [83, 70, 61, 55],
    minutesSaved: 18,
    color: 'orange',
    runBase: 58,
    runTrend: 5,
    history: [
      rel('2.1.0', '2026-06-25', 'Loads the brand kit from the shared token repo instead of a local copy.', 'lucia'),
      rel('2.0.0', '2026-05-19', 'Adds voice and tone checks on top of visual tokens.', 'lucia'),
    ],
  },
  {
    id: 'a11y-audit',
    name: 'Accessibility Audit',
    command: 'a11y-audit',
    tagline: 'WCAG pass with fixes, not just a list of violations.',
    description:
      'Runs an axe pass plus keyboard and screen-reader traversal, then patches what it can: labels, focus order, contrast, landmark structure. Everything it cannot fix safely is left as an annotated TODO.',
    category: 'Design',
    tier: 'official',
    version: '4.0.1',
    updatedAt: '2026-07-19',
    owner: 'dana',
    ownerTeam: 'Design',
    installs: 72,
    activeUsers: 44,
    retention: [90, 81, 75, 69],
    minutesSaved: 52,
    color: 'green',
    runBase: 96,
    runTrend: 11,
    history: [
      rel('4.0.1', '2026-07-19', 'Fixes focus-trap detection inside portalled dialogs.', 'dana'),
      rel('4.0.0', '2026-06-28', 'WCAG 2.2 rule set. Breaking: report schema changed.', 'dana'),
      rel('3.3.0', '2026-05-30', 'Adds screen-reader traversal transcripts.', 'sara'),
    ],
  },
  {
    id: 'copy-tone',
    name: 'Copy Tone Editor',
    command: 'copy-tone',
    tagline: 'Rewrites product and outbound copy in the company voice.',
    description:
      'The most widely installed skill in the company. Takes any text and rewrites it to the internal voice guide: plain words, active verbs, no filler. Works on UI strings, release notes, sales email and legal summaries.',
    category: 'Product',
    tier: 'official',
    version: '5.1.2',
    updatedAt: '2026-07-23',
    owner: 'noor',
    ownerTeam: 'Product',
    installs: 118,
    activeUsers: 94,
    retention: [95, 90, 87, 83],
    minutesSaved: 12,
    color: 'blue',
    runBase: 340,
    runTrend: 18,
    history: [
      rel('5.1.2', '2026-07-23', 'Keeps code identifiers and product names untouched.', 'noor'),
      rel('5.1.0', '2026-07-06', 'Adds a UI-string mode with character budgets.', 'kenji'),
      rel('5.0.0', '2026-06-11', 'New voice guide. Breaking: drops the old `formal` preset.', 'noor'),
    ],
  },
  {
    id: 'release-notes',
    name: 'Release Notes Writer',
    command: 'release-notes',
    tagline: 'Turns a merged diff range into customer-readable notes.',
    description:
      'Reads the commits and PR bodies between two tags, groups them by user-visible impact, and drafts notes in three lengths: changelog line, in-app note, and email paragraph.',
    category: 'Product',
    tier: 'official',
    version: '2.3.0',
    updatedAt: '2026-07-17',
    owner: 'priya',
    ownerTeam: 'Engineering',
    installs: 77,
    activeUsers: 49,
    retention: [87, 78, 72, 66],
    minutesSaved: 46,
    color: 'green',
    runBase: 88,
    runTrend: 9,
    history: [
      rel('2.3.0', '2026-07-17', 'Groups by impact instead of by commit type.', 'priya'),
      rel('2.2.0', '2026-06-20', 'Adds the in-app note length.', 'kenji'),
    ],
  },
  {
    id: 'pr-review',
    name: 'PR Review Agent',
    command: 'pr-review',
    tagline: 'Adversarial diff review that verifies every finding before posting.',
    description:
      'Reviews a branch across correctness, security, performance and test coverage, then runs a second pass that tries to refute each finding. Only findings that survive get posted, which is why the team actually reads them.',
    category: 'Engineering',
    tier: 'official',
    version: '6.4.0',
    updatedAt: '2026-07-22',
    owner: 'jonas',
    ownerTeam: 'Engineering',
    installs: 104,
    activeUsers: 88,
    retention: [96, 92, 89, 86],
    minutesSaved: 63,
    color: 'purple',
    runBase: 410,
    runTrend: 31,
    history: [
      rel('6.4.0', '2026-07-22', 'Adds the refute pass. Cuts false positives by roughly half.', 'jonas'),
      rel('6.2.0', '2026-07-01', 'Reviews only the diff plus its blast radius, not the whole file.', 'tom'),
      rel('6.0.0', '2026-06-09', 'Parallel reviewers per dimension. Breaking: config is now a list.', 'jonas'),
      rel('5.4.0', '2026-05-14', 'Adds security lens with a dependency check.', 'jonas'),
    ],
  },
  {
    id: 'test-gen',
    name: 'Test Generator',
    command: 'test-gen',
    tagline: 'Writes the failing test first, then the tests you forgot.',
    description:
      'Given a change, it generates the regression test that would have caught it, plus edge cases derived from the type signatures. Runs the suite and iterates until green.',
    category: 'Engineering',
    tier: 'official',
    version: '3.5.1',
    updatedAt: '2026-07-11',
    owner: 'tom',
    ownerTeam: 'Engineering',
    installs: 91,
    activeUsers: 67,
    retention: [93, 85, 80, 76],
    minutesSaved: 58,
    color: 'blue',
    runBase: 260,
    runTrend: 21,
    history: [
      rel('3.5.1', '2026-07-11', 'Stops mocking the module under test.', 'tom'),
      rel('3.5.0', '2026-06-24', 'Property-based cases for pure functions.', 'sara'),
      rel('3.0.0', '2026-05-22', 'Vitest first. Breaking: dropped the Jest preset.', 'tom'),
    ],
  },
  {
    id: 'incident-postmortem',
    name: 'Incident Postmortem',
    command: 'incident-postmortem',
    tagline: 'Assembles the timeline from logs, alerts and chat into a blameless doc.',
    description:
      'Pulls the alert timeline, the deploy log and the incident channel, reconstructs what happened minute by minute, and drafts the postmortem with contributing factors and action items already assigned.',
    category: 'Engineering',
    tier: 'official',
    version: '2.2.0',
    updatedAt: '2026-07-08',
    owner: 'priya',
    ownerTeam: 'Engineering',
    installs: 63,
    activeUsers: 31,
    retention: [85, 74, 68, 62],
    minutesSaved: 95,
    color: 'red',
    runBase: 42,
    runTrend: 3,
    history: [
      rel('2.2.0', '2026-07-08', 'Reads the deploy log to correlate the trigger.', 'priya'),
      rel('2.0.0', '2026-06-05', 'Blameless rewrite pass on every draft.', 'priya'),
    ],
  },
  {
    id: 'migration-planner',
    name: 'Migration Planner',
    command: 'migration-planner',
    tagline: 'Finds every call site and sequences the migration into safe steps.',
    description:
      'Maps the full blast radius of an API or schema change across the monorepo, then emits an ordered plan where each step ships independently and is reversible.',
    category: 'Engineering',
    tier: 'recommended',
    version: '1.9.0',
    updatedAt: '2026-06-29',
    owner: 'jonas',
    ownerTeam: 'Engineering',
    installs: 47,
    activeUsers: 26,
    retention: [82, 71, 64, 58],
    minutesSaved: 120,
    color: 'orange',
    runBase: 38,
    runTrend: 4,
    history: [
      rel('1.9.0', '2026-06-29', 'Emits a rollback step for every forward step.', 'jonas'),
      rel('1.6.0', '2026-05-27', 'Adds database schema migrations.', 'tom'),
    ],
  },
  {
    id: 'perf-budget',
    name: 'Performance Budget',
    command: 'perf-budget',
    tagline: 'Fails the build when a change costs more than its budget.',
    description:
      'Measures bundle size, hydration cost and the three core web vitals against a per-route budget, then attributes any regression to the specific import or component that caused it.',
    category: 'Engineering',
    tier: 'recommended',
    version: '2.0.0',
    updatedAt: '2026-07-04',
    owner: 'sara',
    ownerTeam: 'Engineering',
    installs: 39,
    activeUsers: 22,
    retention: [79, 68, 61, 54],
    minutesSaved: 37,
    color: 'pink',
    runBase: 54,
    runTrend: 6,
    history: [
      rel('2.0.0', '2026-07-04', 'Per-route budgets. Breaking: single global budget removed.', 'sara'),
      rel('1.4.0', '2026-06-01', 'Attributes regressions to the import that caused them.', 'sara'),
    ],
  },
  {
    id: 'api-designer',
    name: 'API Designer',
    command: 'api-designer',
    tagline: 'Drafts an endpoint contract that matches the existing house style.',
    description:
      'Reads the neighbouring endpoints, infers the conventions actually in use, and drafts request and response schemas plus error cases that fit. Flags where the new endpoint would break an existing pattern.',
    category: 'Engineering',
    tier: 'experimental',
    version: '0.8.0',
    updatedAt: '2026-07-13',
    owner: 'tom',
    ownerTeam: 'Engineering',
    installs: 24,
    activeUsers: 13,
    retention: [71, 55, 47, 39],
    minutesSaved: 44,
    color: 'grey',
    runBase: 29,
    runTrend: 5,
    history: [
      rel('0.8.0', '2026-07-13', 'Infers pagination style from sibling endpoints.', 'tom'),
      rel('0.5.0', '2026-06-16', 'First internal release.', 'tom'),
    ],
  },
  {
    id: 'prd-writer',
    name: 'PRD Writer',
    command: 'prd-writer',
    tagline: 'Turns a rough idea into a spec engineers will accept.',
    description:
      'Interviews you about the problem, the user and the constraint, then writes the spec: problem statement, scope boundary, open questions, and a testable definition of done. Refuses to write it until the scope boundary is explicit.',
    category: 'Product',
    tier: 'official',
    version: '4.1.0',
    updatedAt: '2026-07-20',
    owner: 'kenji',
    ownerTeam: 'Product',
    installs: 68,
    activeUsers: 43,
    retention: [89, 79, 73, 68],
    minutesSaved: 76,
    color: 'purple',
    runBase: 74,
    runTrend: 8,
    history: [
      rel('4.1.0', '2026-07-20', 'Adds the testable definition of done.', 'kenji'),
      rel('4.0.0', '2026-06-14', 'Interview-first flow. Breaking: no longer accepts a one-shot prompt.', 'kenji'),
    ],
  },
  {
    id: 'user-interview',
    name: 'User Interview Synthesizer',
    command: 'user-interview',
    tagline: 'Clusters interview transcripts into themes with quote evidence.',
    description:
      'Takes raw transcripts and returns the themes ranked by frequency and severity, each backed by verbatim quotes and the interview they came from. Separates what users said from what the interviewer suggested.',
    category: 'Product',
    tier: 'recommended',
    version: '2.6.0',
    updatedAt: '2026-07-10',
    owner: 'noor',
    ownerTeam: 'Product',
    installs: 44,
    activeUsers: 27,
    retention: [84, 72, 66, 60],
    minutesSaved: 88,
    color: 'green',
    runBase: 46,
    runTrend: 6,
    history: [
      rel('2.6.0', '2026-07-10', 'Flags leading questions and discounts those answers.', 'noor'),
      rel('2.4.0', '2026-06-08', 'Adds severity weighting on top of frequency.', 'kenji'),
    ],
  },
  {
    id: 'roadmap-triage',
    name: 'Roadmap Triage',
    command: 'roadmap-triage',
    tagline: 'Scores the backlog against strategy and tells you what to cut.',
    description:
      'Reads the backlog and the current strategy doc, scores every item on reach, confidence and strategic fit, then proposes the cut line with a one-line rationale per item.',
    category: 'Product',
    tier: 'recommended',
    version: '1.7.0',
    updatedAt: '2026-06-27',
    owner: 'kenji',
    ownerTeam: 'Product',
    installs: 36,
    activeUsers: 19,
    retention: [77, 64, 56, 49],
    minutesSaved: 65,
    color: 'orange',
    runBase: 33,
    runTrend: 3,
    history: [
      rel('1.7.0', '2026-06-27', 'Proposes an explicit cut line instead of a ranked list.', 'kenji'),
      rel('1.5.0', '2026-05-25', 'Reads the strategy doc for fit scoring.', 'noor'),
    ],
  },
  {
    id: 'contract-review',
    name: 'Contract Review',
    command: 'contract-review',
    tagline: 'Redlines a vendor contract against the company playbook.',
    description:
      'Compares an inbound contract to the legal playbook, flags every deviation by risk tier, and drafts the redline with fallback language. Escalates anything touching liability, IP or data residency.',
    category: 'Legal',
    tier: 'official',
    version: '3.0.2',
    updatedAt: '2026-07-16',
    owner: 'omar',
    ownerTeam: 'Legal',
    installs: 21,
    activeUsers: 14,
    retention: [91, 83, 78, 73],
    minutesSaved: 145,
    color: 'red',
    runBase: 26,
    runTrend: 2,
    history: [
      rel('3.0.2', '2026-07-16', 'Adds data-residency escalation for EU counterparties.', 'omar'),
      rel('3.0.0', '2026-06-12', 'New playbook. Breaking: risk tiers renumbered.', 'omar'),
    ],
  },
  {
    id: 'policy-diff',
    name: 'Policy Diff',
    command: 'policy-diff',
    tagline: 'Explains what changed in a policy and who it affects.',
    description:
      'Diffs two versions of an internal policy or an external regulation, then writes a plain-language summary of what changed, which teams are affected, and what they need to do differently.',
    category: 'Legal',
    tier: 'recommended',
    version: '1.3.0',
    updatedAt: '2026-06-23',
    owner: 'omar',
    ownerTeam: 'Legal',
    installs: 18,
    activeUsers: 9,
    retention: [74, 61, 52, 45],
    minutesSaved: 54,
    color: 'grey',
    runBase: 17,
    runTrend: 2,
    history: [
      rel('1.3.0', '2026-06-23', 'Maps affected teams from the policy scope table.', 'omar'),
      rel('1.0.0', '2026-05-18', 'First release.', 'yuki'),
    ],
  },
  {
    id: 'sales-email',
    name: 'Sales Email Writer',
    command: 'sales-email',
    tagline: 'Writes outbound that references something real about the account.',
    description:
      'Pulls the account research, the last touchpoint and the product fit, then writes a short outbound email with one specific hook. Rejects any draft that would read as generic.',
    category: 'Sales',
    tier: 'official',
    version: '4.2.0',
    updatedAt: '2026-07-18',
    owner: 'hana',
    ownerTeam: 'Sales',
    installs: 52,
    activeUsers: 40,
    retention: [88, 80, 75, 71],
    minutesSaved: 26,
    color: 'pink',
    runBase: 190,
    runTrend: 16,
    history: [
      rel('4.2.0', '2026-07-18', 'Rejects drafts with no account-specific hook.', 'hana'),
      rel('4.0.0', '2026-06-19', 'Pulls CRM context automatically. Breaking: needs CRM scope.', 'hana'),
    ],
  },
  {
    id: 'deal-brief',
    name: 'Deal Brief',
    command: 'deal-brief',
    tagline: 'One-page brief before every call: history, risk, next best action.',
    description:
      'Assembles everything known about an account into a one-pager: deal history, open objections, competitive position, and the single next action most likely to move it forward.',
    category: 'Sales',
    tier: 'recommended',
    version: '2.5.0',
    updatedAt: '2026-07-09',
    owner: 'ben',
    ownerTeam: 'Sales',
    installs: 34,
    activeUsers: 23,
    retention: [86, 77, 70, 65],
    minutesSaved: 33,
    color: 'blue',
    runBase: 78,
    runTrend: 9,
    history: [
      rel('2.5.0', '2026-07-09', 'Adds competitive position from win/loss notes.', 'ben'),
      rel('2.2.0', '2026-06-07', 'Surfaces open objections from call transcripts.', 'hana'),
    ],
  },
  {
    id: 'vendor-audit',
    name: 'Vendor Audit',
    command: 'vendor-audit',
    tagline: 'Checks spend, usage and renewal risk across every SaaS vendor.',
    description:
      'Cross-references the vendor list with actual seat usage and spend, then flags renewals worth renegotiating and licenses nobody has opened in 60 days.',
    category: 'Ops',
    tier: 'experimental',
    version: '0.6.0',
    updatedAt: '2026-07-05',
    owner: 'yuki',
    ownerTeam: 'Ops',
    installs: 12,
    activeUsers: 7,
    retention: [68, 52, 43, 36],
    minutesSaved: 110,
    color: 'grey',
    runBase: 14,
    runTrend: 1,
    history: [
      rel('0.6.0', '2026-07-05', 'Adds seat-usage cross-reference.', 'yuki'),
      rel('0.3.0', '2026-06-03', 'First internal release.', 'yuki'),
    ],
  },
]

export const skills: Skill[] = seeds.map(({ runBase, runTrend, ...rest }) => ({
  ...rest,
  source: sources[rest.id] ?? { kind: 'internal', team: rest.ownerTeam },
  access: access[rest.id] ?? { scope: 'company' },
  weeklyRuns: weeklySeries(rest.id, runBase, runTrend),
  usedBy: people.filter((p) => p.collection.includes(rest.id)).map((p) => p.id),
}))

export const skillsById: Record<string, Skill> = Object.fromEntries(
  skills.map((s) => [s.id, s]),
)

export const skillColor = (id: string): DitherColor => skillsById[id]?.color ?? 'grey'
